version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: onLine-db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres

  redis:
    container_name: redis_db
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - redis-network

  redis-commander:
    container_name: redis_commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=redis
      - HTTP_PASSWORD=redis
    ports:
      - "8081:8081"
    networks:
      - redis-network
    depends_on:
      - redis

volumes:
  redis:
  redis-config:
  postgres:

networks:
  redis-network:
    driver: bridge