package com.chirko.onLine.exceptions;

public enum ErrorCause {
    ACCESS_DENIED,
    COMMON_TOKEN_EXPIRED,
    COMMON_TOKEN_NOT_FOUND,
    COMMON_TOKEN_INVALID,
    OLD_PASSWORD_INVALID,
    POST_NOT_FOUND,
    USER_ALREADY_EXIST,
    USER_NOT_FOUND,
    IMAGE_NOT_FOUND,
    COMMENT_NOT_FOUND,
    TAG_NOT_FOUND,
    COMMUNITY_NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    ALREADY_LIKED
}
